### ISSUE TITLE
Service (re)Registration Failure

### ISSUE THREAD

**Issue by wmunyan** [opendxl/opendxl-client-java#17]
I have a Grails-based application, deployed on Tomcat 9, using Java 11, and including the latest opendxl-java-client (0.2.5).  A couple of services are registered on application startup and work fine for a time.  When the service registration's TTL expires, though, and the registration thread attempts to re-register the service, I'm receiving the following exception:

```
29/07/2020 11:21:44.132 DEBUG com.opendxl.client.ServiceRegistrationHandler  - Registration thread waiting: 600000, Service registration thread: 1014387494, My Service Name, {457f17a8-a66b-4722-893d-753bf6684959}
29/07/2020 11:21:44.174 ERROR com.opendxl.client.DxlClient  - connectionLost: Connection lost, disconnection strategy will be invoked.
Connection lost (32109) - javax.net.ssl.SSLException: Connection reset
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:189)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1576)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:974)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:865)
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
        ... 6 more
        Suppressed: java.net.SocketException: Broken pipe (Write failed)
                at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
                at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
                at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
                ... 14 more
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
        ... 10 more
29/07/2020 11:21:44.190 DEBUG com.opendxl.client.ServiceRegistrationHandler  - Registration thread exiting: Service registration thread: 1014387494, My Service Name, {457f17a8-a66b-4722-893d-753bf6684959}
```
I've set the TTL to 10 minutes (the minimum) in order to better debug and see this error quicker, but it's received no matter what the TTL.

Any advice on things to check on this?  Configurations of my DXL client?  Any assistance whatsoever would be most helpful.

**Comment by wmunyan** [comment]
Hey all, we've discovered the cause of this issue.  Our deployment infrastructure in AWS is using some internet gateways, which maintain a connection timeout of 350 seconds.  Configuring the DXL client configuration's keep-alive interval (`clientConfig.setKeepAliveInterval(int)`) less than 350 allows the client to maintain its connectivity "heartbeat".
